// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PositionCoachReviewApi.Data;

#nullable disable

namespace PositionCoachReviewApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260111214551_PhotoUpload")]
    partial class PhotoUpload
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("PositionCoachReviewApi.Models.AthleteProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreasForImprovementJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AthleteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxBudgetPerSession")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxTravelDistanceMiles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreferGroupTraining")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreferOneOnOne")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredCoachingStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredCommunicationStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredSchedule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryGoalsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionDuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionsPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialNeeds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainingIntensity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WillingToTravel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Position");

                    b.HasIndex("SkillLevel");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("ZipCode");

                    b.ToTable("AthleteProfiles");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoachId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubscriptionTierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionTierId");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.CoachMatchProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcceptsGroupTraining")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcceptsOneOnOne")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvailableDaysJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvailableTimeSlotsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CoachId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoachingStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommunicationStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAgeAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxNewClientsPerMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinAgeAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OffersInPersonSessions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OffersVirtualSessions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PositionsCoached")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredAthleteTraitsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SessionPriceMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SessionPriceMin")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillLevelsAccepted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialtiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuccessStoriesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainingPhilosophy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TravelRadiusMiles")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("YearsCoachingPosition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoachId")
                        .IsUnique();

                    b.HasIndex("PositionsCoached");

                    b.ToTable("CoachMatchProfiles");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.MatchInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchInteractions");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.MatchModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AthleteInterestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AthleteNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AthleteProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CoachInterestedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CoachMatchProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoachNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchReasonsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MatchScore")
                        .HasColumnType("REAL");

                    b.Property<string>("ScoreBreakdownJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AthleteProfileId");

                    b.HasIndex("CoachMatchProfileId");

                    b.ToTable("MatchModels");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.MatchPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AthleteProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FiltersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferenceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AthleteProfileId");

                    b.ToTable("MatchPreferences");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoachId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.SubscriptionTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnalyticsAccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FeaturedListing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxClients")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionTiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnalyticsAccess = false,
                            Description = "Basic listing with limited features",
                            FeaturedListing = false,
                            MaxClients = 5,
                            Name = "Free",
                            Price = 0m
                        },
                        new
                        {
                            Id = 2,
                            AnalyticsAccess = true,
                            Description = "Enhanced listing with more client slots",
                            FeaturedListing = false,
                            MaxClients = 20,
                            Name = "Basic",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 3,
                            AnalyticsAccess = true,
                            Description = "Full-featured listing with unlimited clients and featured placement",
                            FeaturedListing = true,
                            MaxClients = 999,
                            Name = "Premium",
                            Price = 79.99m
                        });
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.ZipCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ZipCodes");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.AthleteProfile", b =>
                {
                    b.HasOne("PositionCoachReviewApi.Models.User", "User")
                        .WithOne("AthleteProfile")
                        .HasForeignKey("PositionCoachReviewApi.Models.AthleteProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.Client", b =>
                {
                    b.HasOne("PositionCoachReviewApi.Models.Coach", "Coach")
                        .WithMany("Clients")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.Coach", b =>
                {
                    b.HasOne("PositionCoachReviewApi.Models.SubscriptionTier", "SubscriptionTier")
                        .WithMany("Coaches")
                        .HasForeignKey("SubscriptionTierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionTier");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.CoachMatchProfile", b =>
                {
                    b.HasOne("PositionCoachReviewApi.Models.Coach", "Coach")
                        .WithOne("MatchProfile")
                        .HasForeignKey("PositionCoachReviewApi.Models.CoachMatchProfile", "CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.MatchInteraction", b =>
                {
                    b.HasOne("PositionCoachReviewApi.Models.MatchModel", "Match")
                        .WithMany("Interactions")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.MatchModel", b =>
                {
                    b.HasOne("PositionCoachReviewApi.Models.AthleteProfile", "AthleteProfile")
                        .WithMany("Matches")
                        .HasForeignKey("AthleteProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PositionCoachReviewApi.Models.CoachMatchProfile", "CoachMatchProfile")
                        .WithMany("Matches")
                        .HasForeignKey("CoachMatchProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AthleteProfile");

                    b.Navigation("CoachMatchProfile");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.MatchPreference", b =>
                {
                    b.HasOne("PositionCoachReviewApi.Models.AthleteProfile", "AthleteProfile")
                        .WithMany("MatchPreferences")
                        .HasForeignKey("AthleteProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AthleteProfile");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.Review", b =>
                {
                    b.HasOne("PositionCoachReviewApi.Models.Coach", "Coach")
                        .WithMany("Reviews")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PositionCoachReviewApi.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.AthleteProfile", b =>
                {
                    b.Navigation("MatchPreferences");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.Coach", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("MatchProfile");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.CoachMatchProfile", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.MatchModel", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.SubscriptionTier", b =>
                {
                    b.Navigation("Coaches");
                });

            modelBuilder.Entity("PositionCoachReviewApi.Models.User", b =>
                {
                    b.Navigation("AthleteProfile");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
